{
    'name': 'Work Injury',
    'version': '13.0.2.0.0',
    'summary': """Customizing recruitment """,
    'description': 'This module helps you to manager work injury and clinic reports.',
    'category': 'Generic Modules/Human Resources',
    'author': 'BlueHawk consulting',
    'company': 'BlueHawk consulting',
    'depends': ['base', 'hr', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'views/work_injury.xml',
        'views/employee_request.xml',
        'views/canteen_views.xml',
    ],
    'demo': [],
    'images': ['static/description/banner.png'],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
}
